from fastapi import APIRouter, Depends
from middleware.auth import get_current_user
from services.asi_evolve_client import health, evolve
from services.strategy_reference_builder import build_strategy_references
from database import db
from datetime import datetime

router = APIRouter()

@router.get('/health')
async def asi_health(user=Depends(get_current_user)):
    return await health()

@router.get('/references')
async def asi_references(ticker: str | None = None, asset_type: str | None = None, limit: int = 10, user=Depends(get_current_user)):
    return await build_strategy_references(user, ticker=ticker, asset_type=asset_type, limit=limit)

@router.post('/generate-strategy')
async def generate_strategy(req: dict, user=Depends(get_current_user)):
    ticker = req.get('ticker')
    asset_type = req.get('asset_type')
    refs = await build_strategy_references(user, ticker=ticker, asset_type=asset_type, limit=int(req.get('reference_limit', 10)))
    payload = {
        'task': 'generate_strategy',
        'objective': req.get('objective', 'balanced'),
        'generations': int(req.get('generations', 5)),
        'references': refs,
        'notes': req.get('notes', ''),
    }
    out = await evolve(payload, timeout=int(req.get('timeout', 180)))
    if isinstance(out, dict) and not out.get('error') and req.get('save', True):
        strategy = out.get('strategy') or out.get('generated_strategy') or out
        doc = {
            'user_id': user['id'],
            'name': strategy.get('name', 'ASI Generated Strategy') if isinstance(strategy, dict) else 'ASI Generated Strategy',
            'description': strategy.get('description', 'Generated by ASI-Evolve') if isinstance(strategy, dict) else 'Generated by ASI-Evolve',
            'source': 'asi_evolve',
            'ticker': ticker,
            'asset_type': asset_type,
            'parameters': strategy.get('parameters', {}) if isinstance(strategy, dict) else {},
            'rules': {
                'entry_rules': strategy.get('entry_rules', []) if isinstance(strategy, dict) else [],
                'exit_rules': strategy.get('exit_rules', []) if isinstance(strategy, dict) else [],
                'risk_rules': strategy.get('risk_rules', []) if isinstance(strategy, dict) else [],
            },
            'code': strategy.get('code', '') if isinstance(strategy, dict) else '',
            'raw_asi_response': out,
            'created_at': datetime.utcnow().isoformat(),
            'updated_at': datetime.utcnow().isoformat(),
        }
        res = await db['user_strategies'].insert_one(doc)
        doc['_id'] = str(res.inserted_id)
        out['saved_strategy'] = doc
    return out
