from __future__ import annotations

BAYESIAN_VOTING_TEMPLATES = [
    {
        "name": "Bayesian Voting - Balanced",
        "description": "Advanced weighted Bayesian strategy using trend, RSI, MACD, Bollinger, volume and breakout evidence.",
        "template_type": "advanced_python",
        "strategy_slug": "bayesian_voting",
        "min_confidence": 58,
        "params": {
            "buy_threshold": 0.62,
            "sell_threshold": 0.38,
            "min_confidence": 0.58,
            "trend_weight": 1.4,
            "momentum_weight": 1.2,
            "macd_weight": 1.1,
            "volatility_weight": 0.8,
            "volume_weight": 0.7,
            "breakout_weight": 1.0,
            "risk_reward": 1.8,
            "atr_stop_mult": 1.6,
        },
        "rules": [
            {"when": "close > ema(200) and ema(12) > ema(26)", "weight": 40, "side": "BUY"},
            {"when": "rsi > 55 and rsi < 72", "weight": 25, "side": "BUY"},
            {"when": "macd_hist > 0", "weight": 25, "side": "BUY"},
            {"when": "close < ema(200) and ema(12) < ema(26)", "weight": 40, "side": "SELL"},
            {"when": "rsi < 45 and rsi > 28", "weight": 25, "side": "SELL"},
            {"when": "macd_hist < 0", "weight": 25, "side": "SELL"},
        ],
    },
    {
        "name": "Bayesian Voting - Scalping",
        "description": "Faster Bayesian setup for 5m/15m trading with stronger momentum and volume weights.",
        "template_type": "advanced_python",
        "strategy_slug": "bayesian_voting",
        "min_confidence": 62,
        "params": {
            "buy_threshold": 0.64,
            "sell_threshold": 0.36,
            "min_confidence": 0.62,
            "ema_fast": 8,
            "ema_slow": 21,
            "ema_trend": 100,
            "trend_weight": 1.1,
            "momentum_weight": 1.5,
            "macd_weight": 1.2,
            "volume_weight": 1.2,
            "breakout_weight": 1.3,
            "risk_reward": 1.25,
            "atr_stop_mult": 1.1,
        },
        "rules": [
            {"when": "ema(8) > ema(21) and rsi > 52", "weight": 35, "side": "BUY"},
            {"when": "volume > avg_volume(20) * 1.2", "weight": 30, "side": "BUY"},
            {"when": "macd_hist > 0", "weight": 25, "side": "BUY"},
            {"when": "ema(8) < ema(21) and rsi < 48", "weight": 35, "side": "SELL"},
            {"when": "volume > avg_volume(20) * 1.2", "weight": 30, "side": "SELL"},
            {"when": "macd_hist < 0", "weight": 25, "side": "SELL"},
        ],
    },
    {
        "name": "Bayesian Voting - Swing",
        "description": "Slower Bayesian setup for daily swing trades with stronger trend and breakout confirmation.",
        "template_type": "advanced_python",
        "strategy_slug": "bayesian_voting",
        "min_confidence": 60,
        "params": {
            "buy_threshold": 0.63,
            "sell_threshold": 0.37,
            "min_confidence": 0.60,
            "ema_fast": 20,
            "ema_slow": 50,
            "ema_trend": 200,
            "trend_weight": 1.7,
            "momentum_weight": 1.0,
            "macd_weight": 1.0,
            "volume_weight": 0.7,
            "breakout_weight": 1.4,
            "risk_reward": 2.2,
            "atr_stop_mult": 1.8,
        },
        "rules": [
            {"when": "close > ema(200) and ema(20) > ema(50)", "weight": 45, "side": "BUY"},
            {"when": "close > max(highs[-21:-1])", "weight": 35, "side": "BUY"},
            {"when": "adx > 20", "weight": 20, "side": "BUY"},
            {"when": "close < ema(200) and ema(20) < ema(50)", "weight": 45, "side": "SELL"},
            {"when": "close < min(lows[-21:-1])", "weight": 35, "side": "SELL"},
            {"when": "adx > 20", "weight": 20, "side": "SELL"},
        ],
    },
    {
        "name": "Bayesian Voting - Conservative",
        "description": "Higher-confidence Bayesian strategy with strict thresholds and wider ATR stops.",
        "template_type": "advanced_python",
        "strategy_slug": "bayesian_voting",
        "min_confidence": 68,
        "params": {
            "buy_threshold": 0.70,
            "sell_threshold": 0.30,
            "min_confidence": 0.68,
            "trend_weight": 1.8,
            "momentum_weight": 1.0,
            "macd_weight": 1.0,
            "volatility_weight": 0.6,
            "volume_weight": 0.7,
            "breakout_weight": 1.2,
            "risk_reward": 2.0,
            "atr_stop_mult": 2.0,
        },
        "rules": [
            {"when": "close > ema(200) and ema(12) > ema(26) and adx > 22", "weight": 55, "side": "BUY"},
            {"when": "rsi > 58 and macd_hist > 0", "weight": 35, "side": "BUY"},
            {"when": "close < ema(200) and ema(12) < ema(26) and adx > 22", "weight": 55, "side": "SELL"},
            {"when": "rsi < 42 and macd_hist < 0", "weight": 35, "side": "SELL"},
        ],
    },
]
