"""
Autonomous Trading Bots.

A bot is a user-defined recipe that combines strategy, watchlist/symbol universe,
schedule, broker, and sizing/risk rules. The runner evaluates enabled bots on
schedule and can use dynamic watchlists generated by the symbol scanner.
"""
from datetime import datetime
from typing import Optional
from bson import ObjectId
from database import db
from services.logger import child

log = child("bots")
col_bots = db["bots"]
col_executions = db["bot_executions"]

SCHEDULES = {"1m": 60, "5m": 300, "15m": 900, "30m": 1800, "1h": 3600, "4h": 14400, "1d": 86400}
SIZING_MODES = ["fixed_pct", "kelly", "atr_volatility"]
ALLOWED_ASSET_TYPES = ("stock", "crypto", "forex", "oil", "gold", "macro", "future")
ALLOWED_BROKERS = (
    "paper", "alpaca", "binance", "oanda", "fusion",
    "kucoin", "coinbase", "kraken", "bybit", "okx", "bitget", "bitstamp", "gateio",
    "interactive_brokers", "ibkr", "schwab", "tradestation", "tastytrade", "robinhood", "webull", "fidelity", "etrade",
    "fxcm", "forexcom",
)


def _validate_definition(data: dict) -> Optional[str]:
    if not data.get("name") or not isinstance(data["name"], str) or len(data["name"].strip()) == 0:
        return "name is required"
    if len(data["name"]) > 60:
        return "name too long (max 60 chars)"
    strategy_type = data.get("strategy_type", "builtin")
    if strategy_type not in ("builtin", "user"):
        return "strategy_type must be 'builtin' or 'user'"
    if not data.get("strategy_id"):
        return "strategy_id is required"
    watchlist = data.get("watchlist", [])
    use_dynamic = bool(data.get("use_dynamic_watchlist", False))
    if not use_dynamic:
        if not isinstance(watchlist, list) or len(watchlist) == 0:
            return "watchlist must be a non-empty list unless use_dynamic_watchlist=true"
        if len(watchlist) > 50:
            return "watchlist max 50 tickers"
        for item in watchlist:
            if not isinstance(item, dict) or "ticker" not in item:
                return "watchlist items must be {ticker, asset_type}"
            if item.get("asset_type") not in ALLOWED_ASSET_TYPES:
                return f"asset_type must be one of {' | '.join(ALLOWED_ASSET_TYPES)}"
    if data.get("schedule") not in SCHEDULES:
        return f"schedule must be one of {list(SCHEDULES.keys())}"
    if data.get("broker") not in ALLOWED_BROKERS:
        return f"broker must be one of {list(ALLOWED_BROKERS)}"
    sizing_mode = data.get("sizing_mode", "fixed_pct")
    if sizing_mode not in SIZING_MODES:
        return f"sizing_mode must be one of {SIZING_MODES}"
    try:
        sizing_pct = float(data.get("sizing_pct", 1.0))
    except (ValueError, TypeError):
        return "sizing_pct must be numeric"
    if sizing_pct <= 0 or sizing_pct > 50:
        return "sizing_pct must be in (0, 50]"
    try:
        min_conf = int(data.get("min_confidence", 60))
    except (ValueError, TypeError):
        return "min_confidence must be an integer"
    if not 0 <= min_conf <= 100:
        return "min_confidence must be in [0, 100]"
    dyn_asset = data.get("dynamic_asset_type")
    if dyn_asset and dyn_asset not in ALLOWED_ASSET_TYPES:
        return f"dynamic_asset_type must be one of {' | '.join(ALLOWED_ASSET_TYPES)}"
    return None


async def list_bots(user_id: str) -> list:
    docs = await col_bots.find({"user_id": user_id}).sort("created_at", -1).to_list(100)
    for d in docs:
        d["_id"] = str(d["_id"])
    return docs


async def get_bot(user_id: str, bot_id: str) -> Optional[dict]:
    try:
        oid = ObjectId(bot_id)
    except Exception:
        return None
    doc = await col_bots.find_one({"_id": oid, "user_id": user_id})
    if doc:
        doc["_id"] = str(doc["_id"])
    return doc


async def create_bot(user_id: str, data: dict) -> dict:
    err = _validate_definition(data)
    if err:
        return {"error": err}
    if data["strategy_type"] == "user":
        try:
            oid = ObjectId(data["strategy_id"])
        except Exception:
            return {"error": "invalid strategy_id"}
        strat = await db["user_strategies"].find_one({"_id": oid, "user_id": user_id})
        if not strat:
            return {"error": "user strategy not found"}
    enabled = bool(data.get("enabled", False))
    if enabled:
        from services import risk_engine
        if not await risk_engine.is_configured(user_id):
            return {"error": "Risk limits not configured. Set them in Settings before enabling a bot."}
    now = datetime.utcnow().isoformat()
    doc = {
        "user_id": user_id,
        "name": data["name"].strip(),
        "description": (data.get("description") or "").strip()[:240],
        "strategy_type": data["strategy_type"],
        "strategy_id": data["strategy_id"],
        "watchlist": data.get("watchlist", []),
        "use_dynamic_watchlist": bool(data.get("use_dynamic_watchlist", False)),
        "dynamic_asset_type": data.get("dynamic_asset_type"),
        "dynamic_max_watchlist": int(data.get("dynamic_max_watchlist", 10) or 10),
        "schedule": data["schedule"],
        "broker": data["broker"],
        "sizing_mode": data.get("sizing_mode", "fixed_pct"),
        "sizing_pct": float(data.get("sizing_pct", 1.0)),
        "min_confidence": int(data.get("min_confidence", 60)),
        "enabled": enabled,
        "created_at": now,
        "updated_at": now,
        "last_run_at": None,
        "next_run_at": None,
        "stats": {"runs": 0, "signals_fired": 0, "orders_placed": 0, "orders_rejected": 0},
    }
    r = await col_bots.insert_one(doc)
    doc["_id"] = str(r.inserted_id)
    log.info(f"user {user_id} created bot '{doc['name']}' ({doc['_id']}) enabled={enabled}")
    return doc


async def update_bot(user_id: str, bot_id: str, data: dict) -> dict:
    existing = await get_bot(user_id, bot_id)
    if not existing:
        return {"error": "bot not found"}
    merged = {**existing, **data}
    err = _validate_definition(merged)
    if err:
        return {"error": err}
    if data.get("enabled") is True and not existing.get("enabled"):
        from services import risk_engine
        if not await risk_engine.is_configured(user_id):
            return {"error": "Risk limits not configured. Set them in Settings before enabling a bot."}
    allowed = ("name", "description", "strategy_type", "strategy_id", "watchlist", "use_dynamic_watchlist", "dynamic_asset_type", "dynamic_max_watchlist", "schedule", "broker", "sizing_mode", "sizing_pct", "min_confidence", "enabled")
    update = {k: v for k, v in data.items() if k in allowed}
    update["updated_at"] = datetime.utcnow().isoformat()
    await col_bots.update_one({"_id": ObjectId(bot_id), "user_id": user_id}, {"$set": update})
    log.info(f"user {user_id} updated bot {bot_id}: {list(update.keys())}")
    return await get_bot(user_id, bot_id)


async def delete_bot(user_id: str, bot_id: str) -> dict:
    try:
        oid = ObjectId(bot_id)
    except Exception:
        return {"error": "invalid bot_id"}
    res = await col_bots.delete_one({"_id": oid, "user_id": user_id})
    if res.deleted_count == 0:
        return {"error": "bot not found"}
    await col_executions.delete_many({"user_id": user_id, "bot_id": bot_id})
    log.info(f"user {user_id} deleted bot {bot_id}")
    return {"deleted": 1}


async def toggle_bot(user_id: str, bot_id: str, enabled: bool) -> dict:
    return await update_bot(user_id, bot_id, {"enabled": bool(enabled)})


async def get_executions(user_id: str, bot_id: str, limit: int = 50) -> list:
    docs = await col_executions.find({"user_id": user_id, "bot_id": bot_id}).sort("ran_at", -1).limit(limit).to_list(limit)
    for d in docs:
        d["_id"] = str(d["_id"])
    return docs


async def record_execution(user_id: str, bot_id: str, ticker: str, asset_type: str, signal: str, confidence: float, action: str, order_result: Optional[dict] = None, reason: str = "") -> str:
    doc = {"user_id": user_id, "bot_id": bot_id, "ticker": ticker.upper(), "asset_type": asset_type, "signal": signal, "confidence": float(confidence), "action": action, "reason": reason, "order_result": order_result, "ran_at": datetime.utcnow().isoformat()}
    r = await col_executions.insert_one(doc)
    return str(r.inserted_id)


async def get_active_bots() -> list:
    docs = await col_bots.find({"enabled": True}).to_list(1000)
    for d in docs:
        d["_id"] = str(d["_id"])
    return docs
