import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ExternalLink, RefreshCw } from 'lucide-react'
import { api } from '@/store/auth'

const card={background:'#161b22',border:'1px solid #21262d',borderRadius:12,padding:'16px 18px'}
const money=v=>Number.isFinite(Number(v))?`$${Number(v).toFixed(4)}`:'—'
const pct=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(2)}%`:'—'
const sigColor=s=>String(s||'').includes('BUY')?'#3fb950':String(s||'').includes('SELL')?'#f85149':'#8b949e'
const monColor=s=>s==='will_close_now'?'#f85149':s==='near_sl'?'#e3b341':s==='near_tp'?'#3fb950':s==='no_live_price'?'#8b949e':'#58a6ff'
const pill=(txt,bg='#21262d',fg='#e2e8f0')=><span style={{background:bg,color:fg,padding:'3px 8px',borderRadius:999,fontSize:11,fontWeight:700,textTransform:'capitalize'}}>{txt}</span>
const inspect=t=><Link to={`/trade/open/${t._id||t.trade_id||t.id}`} style={{color:'#58a6ff',fontSize:11,textDecoration:'none',display:'inline-flex',alignItems:'center',gap:4,marginTop:8}}>Inspect chart <ExternalLink size={10}/></Link>

export default function AutoTraderLiveOpenTrades(){
  const [trades,setTrades]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[updated,setUpdated]=useState(null)
  async function load(){setLoading(true);setError('');try{const r=await api.get('/autotrader/open-trades/live');setTrades(r.data?.trades||[]);setUpdated(r.data?.updated_at||new Date().toISOString())}catch(e){setError(e?.response?.data?.detail||e.message||'Failed to load live open trades')}setLoading(false)}
  async function monitorNow(){try{await api.post('/autotrader/monitor-now');await load()}catch(e){setError(e?.response?.data?.detail||e.message||'Monitor failed')}}
  useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[])
  return <div style={card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14,gap:8,flexWrap:'wrap'}}><div><div style={{fontSize:13,fontWeight:700,color:'#e2e8f0'}}>Live Open Positions ({trades.length})</div><div style={{fontSize:11,color:'#8b949e'}}>auto-refresh 10s{updated?` · ${new Date(updated).toLocaleTimeString()}`:''}</div></div><div style={{display:'flex',gap:8}}><button onClick={load} disabled={loading} style={{padding:'6px 10px',borderRadius:7,border:'1px solid #30363d',background:'#0d1117',color:'#8b949e',cursor:'pointer',fontSize:12,display:'flex',alignItems:'center',gap:5}}><RefreshCw size={12}/> Refresh</button><button onClick={monitorNow} style={{padding:'6px 10px',borderRadius:7,border:'1px solid #30363d',background:'#21262d',color:'#e2e8f0',cursor:'pointer',fontSize:12}}>Monitor Now</button></div></div>{error&&<div style={{color:'#f85149',fontSize:12,marginBottom:10}}>{error}</div>}{trades.length===0?<div style={{color:'#8b949e',fontSize:13}}>No open trades</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:10}}>{trades.map((t,i)=><div key={t._id||i} style={{background:'#0d1117',border:`1px solid ${monColor(t.monitor_status)}`,borderRadius:10,padding:12}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><div><div style={{fontSize:15,fontWeight:800,color:'#e2e8f0'}}>{t.ticker} <span style={{color:sigColor(t.signal),fontSize:12}}>{t.signal}</span></div><div style={{fontSize:11,color:'#8b949e'}}>{t.asset_type} · {t.timeframe||'—'} · {t.broker_status||'app_managed'}</div></div>{pill(String(t.monitor_status||'open').replace(/_/g,' '),'rgba(88,166,255,.10)',monColor(t.monitor_status))}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:10,fontSize:11,color:'#8b949e'}}><div>Entry<br/><b style={{color:'#e2e8f0'}}>{money(t.entry_price)}</b></div><div>Live<br/><b style={{color:'#e2e8f0'}}>{money(t.live_price)}</b></div><div>PnL %<br/><b style={{color:(t.pnl_pct||0)>=0?'#3fb950':'#f85149'}}>{pct(t.pnl_pct)}</b></div><div>PnL $<br/><b style={{color:(t.pnl_usd||0)>=0?'#3fb950':'#f85149'}}>{money(t.pnl_usd)}</b></div><div>TP<br/><b style={{color:'#3fb950'}}>{money(t.tp)} · {pct(t.distance_to_tp_pct)} away</b></div><div>SL<br/><b style={{color:'#f85149'}}>{money(t.sl)} · {pct(t.distance_to_sl_pct)} away</b></div></div><div style={{fontSize:11,color:'#8b949e',marginTop:10}}>Close rule: <b style={{color:'#e2e8f0'}}>{t.next_close_condition||'—'}</b><br/>Price source: <b style={{color:'#e2e8f0'}}>{t.price_source||'—'}</b>{t.price_age_sec!=null?` · age ${Math.round(t.price_age_sec)}s`:''}</div>{t.should_close_now&&<div style={{marginTop:8,color:'#f85149',fontWeight:800,fontSize:12}}>⚠ Should close now: {t.close_trigger}</div>}{inspect(t)}</div>)}</div>}</div>
}
