import React, { useEffect, useRef, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { createChart } from 'lightweight-charts'
import { api } from '@/store/auth'
import { ArrowLeft, RefreshCw } from 'lucide-react'

const card={background:'#161b22',border:'1px solid #21262d',borderRadius:12,padding:'16px 18px'}
const fmt=v=>Number.isFinite(Number(v))?Number(v).toFixed(4):'—'
const pct=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(2)}%`:'—'
const lineColor=k=>k==='sl'?'#f85149':k==='tp'?'#3fb950':k==='exit'?'#e3b341':'#58a6ff'

export default function TradeInspector(){
 const {source,tradeId}=useParams(); const ref=useRef(null); const chartRef=useRef(null); const [data,setData]=useState(null); const [err,setErr]=useState(''); const [loading,setLoading]=useState(true)
 async function load(){setLoading(true);setErr('');try{const r=await api.get(`/trades/inspect/${encodeURIComponent(source)}/${encodeURIComponent(tradeId)}`);setData(r.data)}catch(e){setErr(e?.response?.data?.detail||e.message||'Failed to load trade')}setLoading(false)}
 useEffect(()=>{load()},[source,tradeId])
 useEffect(()=>{if(!data||!ref.current)return;ref.current.innerHTML='';const chart=createChart(ref.current,{height:520,layout:{background:{color:'#0d1117'},textColor:'#8b949e'},grid:{vertLines:{color:'#21262d'},horzLines:{color:'#21262d'}},rightPriceScale:{borderColor:'#30363d'},timeScale:{borderColor:'#30363d',timeVisible:true,secondsVisible:false}});chartRef.current=chart;const candles=chart.addCandlestickSeries({upColor:'#3fb950',downColor:'#f85149',borderVisible:false,wickUpColor:'#3fb950',wickDownColor:'#f85149'});candles.setData((data.candles||[]).map(c=>({time:c.time,open:Number(c.open),high:Number(c.high),low:Number(c.low),close:Number(c.close)})));candles.setMarkers((data.markers||[]).map(m=>({time:m.time,position:m.position||'aboveBar',color:m.color||'#58a6ff',shape:m.shape||'arrowUp',text:m.text||''})));(data.price_lines||[]).forEach(l=>{if(Number.isFinite(Number(l.price)))candles.createPriceLine({price:Number(l.price),color:l.color||lineColor(l.key),lineWidth:2,lineStyle:2,axisLabelVisible:true,title:l.title||l.key})});chart.timeScale().fitContent();const ro=new ResizeObserver(()=>chart.applyOptions({width:ref.current.clientWidth}));ro.observe(ref.current);return()=>{ro.disconnect();chart.remove()}},[data])
 const t=data?.trade||{}
 return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div><Link to="/autotrader" style={{color:'#8b949e',fontSize:12,textDecoration:'none',display:'inline-flex',gap:6,alignItems:'center'}}><ArrowLeft size={13}/> Back</Link><h1 style={{fontSize:22,color:'#e2e8f0',margin:'8px 0 0'}}>📈 Trade Inspector</h1><div style={{fontSize:12,color:'#8b949e'}}>{source} · {tradeId}</div></div><button onClick={load} style={{padding:'8px 12px',borderRadius:8,border:'1px solid #30363d',background:'#21262d',color:'#e2e8f0',display:'flex',gap:6,alignItems:'center'}}><RefreshCw size={13}/> Refresh</button></div>{loading&&<div style={card}>Loading chart…</div>}{err&&<div style={{...card,borderColor:'#f85149',color:'#f85149'}}>{err}</div>}{data&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10,marginBottom:14}}>{[['Ticker',t.ticker],['Signal',t.signal||t.side],['Status',t.status],['Entry',fmt(t.entry_price||t.entry)],['Exit',fmt(t.close_price||t.exit_price)],['SL',fmt(t.sl||t.stop_loss)],['TP',fmt(t.tp||t.take_profit)],['PnL',pct(t.pnl_pct)],['Outcome',t.outcome||'—'],['Timeframe',t.timeframe||'—']].map(([k,v])=><div key={k} style={{...card,padding:'10px 12px'}}><div style={{fontSize:10,color:'#8b949e',textTransform:'uppercase'}}>{k}</div><div style={{fontSize:16,color:'#e2e8f0',fontWeight:800,marginTop:4}}>{v??'—'}</div></div>)}</div><div style={card}><div ref={ref} style={{width:'100%',height:520}}/></div><div style={{...card,marginTop:14}}><div style={{fontSize:14,fontWeight:800,color:'#e2e8f0',marginBottom:10}}>Raw trade details</div><pre style={{whiteSpace:'pre-wrap',fontSize:12,color:'#8b949e',margin:0}}>{JSON.stringify(t,null,2)}</pre></div></>}</div>
}
