"""Google Colab ASI-Evolve server template.
Run this in Colab, expose with ngrok or Cloudflare Tunnel, then set backend env:
ASI_EVOLVE_URL=https://your-public-url
ASI_EVOLVE_TOKEN=change-me

Endpoints:
GET /health
POST /evolve
"""
import os, random, time
from typing import Dict, Any
from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel
import uvicorn

TOKEN = os.getenv('ASI_EVOLVE_TOKEN', 'change-me')
app = FastAPI(title='ASI-Evolve Colab Server', version='0.1')

class EvolveRequest(BaseModel):
    task: str = 'generate_strategy'
    objective: str = 'balanced'
    generations: int = 5
    references: Dict[str, Any] = {}
    notes: str = ''

def check_auth(authorization: str | None):
    if TOKEN and TOKEN != 'change-me':
        if authorization != f'Bearer {TOKEN}':
            raise HTTPException(401, 'Invalid ASI token')

def pick_indicator(refs):
    inds = refs.get('strategy_contract', {}).get('tradingview_style_indicators', [])
    return random.choice(inds)['name'] if inds else random.choice(['RSI','MACD','EMA','ATR','Supertrend'])

def generate_strategy(req: EvolveRequest):
    refs = req.references or {}
    ind1 = pick_indicator(refs); ind2 = pick_indicator(refs)
    name = f"ASI {ind1} {ind2} Adaptive Strategy"
    code = f"""
def strategy(df, params=None):
    import numpy as np
    import pandas as pd
    params = params or {{}}
    ema_fast = int(params.get('ema_fast', 20))
    ema_slow = int(params.get('ema_slow', 50))
    rsi_window = int(params.get('rsi_window', 14))
    min_volume_ratio = float(params.get('min_volume_ratio', 1.0))
    close = df['close']
    volume = df.get('volume', pd.Series([0]*len(df)))
    ema_f = close.ewm(span=ema_fast, adjust=False).mean()
    ema_s = close.ewm(span=ema_slow, adjust=False).mean()
    delta = close.diff()
    gain = delta.clip(lower=0).rolling(rsi_window).mean()
    loss = (-delta.clip(upper=0)).rolling(rsi_window).mean()
    rsi = 100 - (100 / (1 + (gain / loss.replace(0, np.nan))))
    vr = volume / volume.rolling(20).mean().replace(0, np.nan)
    if len(df) < max(ema_slow, rsi_window) + 2:
        return {{'signal': 'HOLD', 'confidence': 0, 'atr_pct': 1}}
    bullish = ema_f.iloc[-1] > ema_s.iloc[-1] and rsi.iloc[-1] > 52 and vr.iloc[-1] >= min_volume_ratio
    bearish = ema_f.iloc[-1] < ema_s.iloc[-1] and rsi.iloc[-1] < 48 and vr.iloc[-1] >= min_volume_ratio
    if bullish:
        return {{'signal': 'BUY', 'confidence': int(min(95, 55 + (rsi.iloc[-1]-50)*1.2)), 'atr_pct': 1.4}}
    if bearish:
        return {{'signal': 'SELL', 'confidence': int(min(95, 55 + (50-rsi.iloc[-1])*1.2)), 'atr_pct': 1.4}}
    return {{'signal': 'HOLD', 'confidence': 20, 'atr_pct': 1.0}}
""".strip()
    return {
        'strategy': {
            'name': name,
            'description': f'Generated by ASI-Evolve using {ind1}, {ind2}, local OHLCV indicators and objective {req.objective}.',
            'parameters': {
                'ema_fast': {'default': 20, 'range': [8, 30]},
                'ema_slow': {'default': 50, 'range': [35, 120]},
                'rsi_window': {'default': 14, 'range': [7, 28]},
                'min_volume_ratio': {'default': 1.0, 'range': [0.8, 2.0]},
            },
            'entry_rules': ['EMA fast above slow + RSI confirmation + volume filter for long', 'EMA fast below slow + RSI confirmation + volume filter for short'],
            'exit_rules': ['Backend handles SL/TP/time exits; strategy emits reversals and hold'],
            'risk_rules': ['Use ATR stop/take-profit from backend', 'Avoid entries below volume threshold'],
            'code': code,
        },
        'fitness': None,
        'generations': req.generations,
        'notes': req.notes,
    }

@app.get('/health')
def health():
    return {'status': 'ok', 'version': '0.1', 'gpu': False, 'time': time.time()}

@app.post('/evolve')
def evolve(req: EvolveRequest, authorization: str | None = Header(default=None)):
    check_auth(authorization)
    if req.task != 'generate_strategy':
        return {'error': f'Unsupported task: {req.task}'}
    return generate_strategy(req)

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=int(os.getenv('PORT', '8000')))
